[workspace]
members = [
    "pattern-streams",
    "pattern-streams-macros",
    "unreal-sdk",
    "unreal-camera-injector",
    "unreal-vr-core",
    "unreal-vr-launcher"
]

[profile.dev-opt]
inherits = "dev"
opt-level = 3
lto = true
