[workspace]
members = [
    "asm-analyzer",
    "unreal-sdk",
    "unreal-camera-injector",
    "unreal-vr-runtime",
    "unreal-vr-launcher"
]

[profile.dev-opt]
inherits = "dev"
opt-level = 3
lto = true
