imports_granularity = "Module"
group_imports = "StdExternalCrate"
wrap_comments = true
normalize_doc_attributes = true
normalize_comments = true
reorder_impl_items = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
use_try_shorthand = true
hide_parse_errors = true
